### ISSUE TITLE
Tidak dapat diakses dari luar

### ISSUE THREAD

**Issue by sigitwh** [apolbox/termux-webserver#11]
Setelah di install, bisa berjalan di browser Androidnya.
Tapi tidak bisa diakses dari luar lewat tethering ataupun WiFi.

Caranya bagaimana supaya bisa diakses dari luar lewat tethering ataupun WiFi

**Comment by wadahkode** [comment]
Mohon maaf kalau balasnya lama,

Agar dapat digunakan dari luar kamu harus mendapatkan ip public terlebih dahulu.

Kamu bisa cari digoogle cara untuk mendapatkan ip public, setelah itu baru bisa digunakan dari luar.

contoh :

192.168.1.1:8080 = localhost:8080
