### ISSUE TITLE
phpmyadmin 

### ISSUE THREAD

**Issue by RvXRN** [apolbox/termux-webserver#15]
kok punya saya localhost phpmyadmin nya 404 not found ya
![Screenshot_20231026_165044_Chrome](https://github.com/apolbox/termux-webserver/assets/112039501/ff09a1ef-15c8-472a-bc79-db945965d844)
padahal dah jalan
![Screenshot_20231026_165226_Termux](https://github.com/apolbox/termux-webserver/assets/112039501/cd898080-6df8-4743-96d6-0b85430379e3)

**Comment by LzkRn** [comment]
tinggal di update ternyata
